import type { Dealer } from "@/lib/types";

// PLACEHOLDER: confirm with AIPL before launch — these are placeholder dealer locations pending the client's actual dealer list
export const dealers: Dealer[] = [
  {
    id: "dealer-001",
    name: "AIPL Kathmandu Central",
    province: "Bagmati Province",
    district: "Kathmandu",
    municipality: "Kathmandu Metropolitan City",
    ward: 10,
    address: "New Baneshwor, Kathmandu",
    phone: "+977-01-XXXXXXX",
    email: "kathmandu@aipl.com.np",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dealer-002",
    name: "AIPL Lalitpur Dealer",
    province: "Bagmati Province",
    district: "Lalitpur",
    municipality: "Lalitpur Metropolitan City",
    ward: 5,
    address: "Pulchowk, Lalitpur",
    phone: "+977-01-XXXXXXX",
    email: "lalitpur@aipl.com.np",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dealer-003",
    name: "AIPL Bhaktapur Dealer",
    province: "Bagmati Province",
    district: "Bhaktapur",
    municipality: "Bhaktapur Municipality",
    ward: 3,
    address: "Suryabinayak, Bhaktapur",
    phone: "+977-01-XXXXXXX",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dealer-004",
    name: "AIPL Pokhara Dealer",
    province: "Gandaki Province",
    district: "Kaski",
    municipality: "Pokhara Metropolitan City",
    ward: 8,
    address: "Lakeside Road, Pokhara",
    phone: "+977-061-XXXXXXX",
    email: "pokhara@aipl.com.np",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dealer-005",
    name: "AIPL Biratnagar Dealer",
    province: "Koshi Province",
    district: "Morang",
    municipality: "Biratnagar Metropolitan City",
    ward: 12,
    address: "Main Road, Biratnagar",
    phone: "+977-021-XXXXXXX",
    email: "biratnagar@aipl.com.np",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dealer-006",
    name: "AIPL Dharan Dealer",
    province: "Koshi Province",
    district: "Sunsari",
    municipality: "Dharan Sub-Metropolitan City",
    ward: 6,
    address: "Putali Line, Dharan",
    phone: "+977-025-XXXXXXX",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dealer-007",
    name: "AIPL Chitwan Dealer",
    province: "Bagmati Province",
    district: "Chitwan",
    municipality: "Bharatpur Metropolitan City",
    ward: 4,
    address: "Narayangadh, Chitwan",
    phone: "+977-056-XXXXXXX",
    email: "chitwan@aipl.com.np",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dealer-008",
    name: "AIPL Butwal Dealer",
    province: "Lumbini Province",
    district: "Rupandehi",
    municipality: "Butwal Sub-Metropolitan City",
    ward: 9,
    address: "Traffic Chowk, Butwal",
    phone: "+977-071-XXXXXXX",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dealer-009",
    name: "AIPL Nepalgunj Dealer",
    province: "Lumbini Province",
    district: "Banke",
    municipality: "Nepalgunj Sub-Metropolitan City",
    ward: 7,
    address: "Surkhet Road, Nepalgunj",
    phone: "+977-081-XXXXXXX",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dealer-010",
    name: "AIPL Dhangadhi Dealer",
    province: "Sudurpashchim Province",
    district: "Kailali",
    municipality: "Dhangadhi Sub-Metropolitan City",
    ward: 5,
    address: "Main Bazaar, Dhangadhi",
    phone: "+977-091-XXXXXXX",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dealer-011",
    name: "AIPL Janakpur Dealer",
    province: "Madhesh Province",
    district: "Dhanusha",
    municipality: "Janakpur Sub-Metropolitan City",
    ward: 11,
    address: "Station Road, Janakpur",
    phone: "+977-041-XXXXXXX",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dealer-012",
    name: "AIPL Birgunj Dealer",
    province: "Madhesh Province",
    district: "Parsa",
    municipality: "Birgunj Metropolitan City",
    ward: 8,
    address: "Adarsha Nagar, Birgunj",
    phone: "+977-051-XXXXXXX",
    email: "birgunj@aipl.com.np",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dealer-013",
    name: "AIPL Hetauda Dealer",
    province: "Bagmati Province",
    district: "Makwanpur",
    municipality: "Hetauda Sub-Metropolitan City",
    ward: 3,
    address: "Industrial Area, Hetauda",
    phone: "+977-057-XXXXXXX",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dealer-014",
    name: "AIPL Surkhet Dealer",
    province: "Karnali Province",
    district: "Surkhet",
    municipality: "Birendranagar Municipality",
    ward: 6,
    address: "Mangalgadhi, Birendranagar",
    phone: "+977-083-XXXXXXX",
    createdAt: "2024-01-01T00:00:00Z",
  },
];
