export interface Province {
  id: number;
  name: string;
  districts: District[];
}

export interface District {
  id: number;
  name: string;
  municipalities: Municipality[];
}

export interface Municipality {
  id: number;
  name: string;
  type: "metropolitan" | "sub-metropolitan" | "municipality" | "rural-municipality";
  wards: number;
}

export const provinces: Province[] = [
  {
    id: 1,
    name: "Koshi Pradesh",
    districts: [
      {
        id: 1,
        name: "Taplejung",
        municipalities: [
          { id: 1, name: "Phungling Municipality", type: "municipality", wards: 11 },
          { id: 2, name: "Aathrai Triveni Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 3, name: "Sidingba Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 4, name: "Phaktanglung Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 5, name: "Mikwakhola Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 6, name: "Meringden Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 7, name: "Maiwakhola Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 8, name: "Pathivara Yangwarak Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 9, name: "Sirijangha Rural Municipality", type: "rural-municipality", wards: 6 },
        ],
      },
      {
        id: 2,
        name: "Panchthar",
        municipalities: [
          { id: 10, name: "Phidim Municipality", type: "municipality", wards: 14 },
          { id: 11, name: "Hilihang Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 12, name: "Falelung Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 13, name: "Falgunanda Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 14, name: "Kummayak Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 15, name: "Miklajung Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 16, name: "Tumbewa Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 17, name: "Yangwarak Rural Municipality", type: "rural-municipality", wards: 7 },
        ],
      },
      {
        id: 3,
        name: "Ilam",
        municipalities: [
          { id: 18, name: "Ilam Municipality", type: "municipality", wards: 12 },
          { id: 19, name: "Deumai Municipality", type: "municipality", wards: 12 },
          { id: 20, name: "Mai Municipality", type: "municipality", wards: 11 },
          { id: 21, name: "Suryodaya Municipality", type: "municipality", wards: 14 },
          { id: 22, name: "Mangsebung Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 23, name: "Rong Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 24, name: "Maijogmai Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 25, name: "Chulachuli Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 26, name: "Sandakpur Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 27, name: "Fakphokthum Rural Municipality", type: "rural-municipality", wards: 7 },
        ],
      },
      {
        id: 4,
        name: "Jhapa",
        municipalities: [
          { id: 28, name: "Mechinagar Municipality", type: "municipality", wards: 15 },
          { id: 29, name: "Bhadrapur Municipality", type: "municipality", wards: 10 },
          { id: 30, name: "Birtamod Municipality", type: "municipality", wards: 11 },
          { id: 31, name: "Damak Municipality", type: "municipality", wards: 11 },
          { id: 32, name: "Kankai Municipality", type: "municipality", wards: 10 },
          { id: 33, name: "Shivasatakshi Municipality", type: "municipality", wards: 11 },
          { id: 34, name: "Arjundhara Municipality", type: "municipality", wards: 11 },
          { id: 35, name: "Kamal Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 36, name: "Buddhashanti Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 37, name: "Kachankawal Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 38, name: "Gauradaha Municipality", type: "municipality", wards: 9 },
          { id: 39, name: "Haldibari Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 40, name: "Jhapa Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 41, name: "Barhadashi Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 42, name: "Gauradhaha Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 5,
        name: "Morang",
        municipalities: [
          { id: 43, name: "Biratnagar Metropolitan City", type: "metropolitan", wards: 19 },
          { id: 44, name: "Sundar Haraicha Municipality", type: "municipality", wards: 12 },
          { id: 45, name: "Belbari Municipality", type: "municipality", wards: 11 },
          { id: 46, name: "Pathari Sanischare Municipality", type: "municipality", wards: 13 },
          { id: 47, name: "Urlabari Municipality", type: "municipality", wards: 13 },
          { id: 48, name: "Rangeli Municipality", type: "municipality", wards: 10 },
          { id: 49, name: "Letang Municipality", type: "municipality", wards: 10 },
          { id: 50, name: "Ratuwamai Municipality", type: "municipality", wards: 10 },
          { id: 51, name: "Sunbarshi Municipality", type: "municipality", wards: 12 },
          { id: 52, name: "Katahari Rural Municipality", type: "rural-municipality", wards: 11 },
          { id: 53, name: "Gramthan Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 54, name: "Dhanpalthan Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 55, name: "Kerabari Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 56, name: "Budhiganga Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 57, name: "Kanepokhari Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 58, name: "Miklajung Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 59, name: "Jahada Rural Municipality", type: "rural-municipality", wards: 7 },
        ],
      },
      {
        id: 6,
        name: "Sunsari",
        municipalities: [
          { id: 60, name: "Dharan Sub-Metropolitan City", type: "sub-metropolitan", wards: 20 },
          { id: 61, name: "Itahari Sub-Metropolitan City", type: "sub-metropolitan", wards: 20 },
          { id: 62, name: "Inaruwa Municipality", type: "municipality", wards: 10 },
          { id: 63, name: "Duhabi Municipality", type: "municipality", wards: 11 },
          { id: 64, name: "Ramdhuni Municipality", type: "municipality", wards: 9 },
          { id: 65, name: "Barahakshetra Municipality", type: "municipality", wards: 11 },
          { id: 66, name: "Dewanganj Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 67, name: "Koshi Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 68, name: "Gadhi Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 69, name: "Barju Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 70, name: "Bhokraha Narsimha Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 71, name: "Harinagara Rural Municipality", type: "rural-municipality", wards: 6 },
        ],
      },
      {
        id: 7,
        name: "Dhankuta",
        municipalities: [
          { id: 72, name: "Dhankuta Municipality", type: "municipality", wards: 10 },
          { id: 73, name: "Pakhribas Municipality", type: "municipality", wards: 10 },
          { id: 74, name: "Mahalaxmi Municipality", type: "municipality", wards: 10 },
          { id: 75, name: "Sangurigadhi Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 76, name: "Chhathar Jorpati Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 77, name: "Sahidbhumi Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 78, name: "Khalsa Chhintang Sahidbhumi Rural Municipality", type: "rural-municipality", wards: 6 },
        ],
      },
      {
        id: 8,
        name: "Terhathum",
        municipalities: [
          { id: 79, name: "Myanglung Municipality", type: "municipality", wards: 10 },
          { id: 80, name: "Laligurans Municipality", type: "municipality", wards: 9 },
          { id: 81, name: "Aathrai Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 82, name: "Chhathar Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 83, name: "Phedap Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 84, name: "Menchayam Rural Municipality", type: "rural-municipality", wards: 6 },
        ],
      },
      {
        id: 9,
        name: "Sankhuwasabha",
        municipalities: [
          { id: 85, name: "Khandbari Municipality", type: "municipality", wards: 11 },
          { id: 86, name: "Chainpur Municipality", type: "municipality", wards: 12 },
          { id: 87, name: "Dharmadevi Municipality", type: "municipality", wards: 9 },
          { id: 88, name: "Panchkhapan Municipality", type: "municipality", wards: 9 },
          { id: 89, name: "Madi Municipality", type: "municipality", wards: 10 },
          { id: 90, name: "Makalu Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 91, name: "Sabhapokhari Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 92, name: "Bhotkhola Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 93, name: "Chichila Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 94, name: "Silichong Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 10,
        name: "Bhojpur",
        municipalities: [
          { id: 95, name: "Bhojpur Municipality", type: "municipality", wards: 10 },
          { id: 96, name: "Shadananda Municipality", type: "municipality", wards: 10 },
          { id: 97, name: "Tyamke Maiyunm Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 98, name: "Ramprasad Rai Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 99, name: "Aamchowk Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 100, name: "Hatuwagadhi Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 101, name: "Pauwadungma Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 102, name: "Salpasilichho Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 103, name: "Arun Rural Municipality", type: "rural-municipality", wards: 7 },
        ],
      },
      {
        id: 11,
        name: "Solukhumbu",
        municipalities: [
          { id: 104, name: "Solududhkunda Municipality", type: "municipality", wards: 11 },
          { id: 105, name: "Dudhakaushika Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 106, name: "Necha Salyan Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 107, name: "Dudhkoshi Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 108, name: "Mahakulung Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 109, name: "Sotang Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 110, name: "Khumbu Pasanglhamu Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 111, name: "Likhu Pike Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 12,
        name: "Okhaldhunga",
        municipalities: [
          { id: 112, name: "Siddhicharan Municipality", type: "municipality", wards: 11 },
          { id: 113, name: "Khiji Demba Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 114, name: "Chisankhugadhi Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 115, name: "Molung Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 116, name: "Champadevi Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 117, name: "Sunkoshi Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 118, name: "Likhu Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 119, name: "Manebhanjyang Rural Municipality", type: "rural-municipality", wards: 6 },
        ],
      },
      {
        id: 13,
        name: "Khotang",
        municipalities: [
          { id: 120, name: "Diktel Rupakot Majhuwagadhi Municipality", type: "municipality", wards: 13 },
          { id: 121, name: "Halesi Tuwachung Municipality", type: "municipality", wards: 10 },
          { id: 122, name: "Khotehang Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 123, name: "Diprung Chuichumma Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 124, name: "Ainselukhark Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 125, name: "Jantedhunga Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 126, name: "Kepilasgadhi Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 127, name: "Barahapokhari Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 128, name: "Rawabesi Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 129, name: "Sakela Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 14,
        name: "Udayapur",
        municipalities: [
          { id: 130, name: "Triyuga Municipality", type: "municipality", wards: 15 },
          { id: 131, name: "Katari Municipality", type: "municipality", wards: 11 },
          { id: 132, name: "Chaudandigadhi Municipality", type: "municipality", wards: 10 },
          { id: 133, name: "Belaka Municipality", type: "municipality", wards: 10 },
          { id: 134, name: "Udayapurgadhi Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 135, name: "Rautamai Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 136, name: "Tapli Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 137, name: "Limchungbung Rural Municipality", type: "rural-municipality", wards: 6 },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Madhesh Pradesh",
    districts: [
      {
        id: 15,
        name: "Saptari",
        municipalities: [
          { id: 138, name: "Rajbiraj Municipality", type: "municipality", wards: 15 },
          { id: 139, name: "Kanchanrup Municipality", type: "municipality", wards: 11 },
          { id: 140, name: "Dakneshwori Municipality", type: "municipality", wards: 11 },
          { id: 141, name: "Bodebarsain Municipality", type: "municipality", wards: 10 },
          { id: 142, name: "Shambhunath Municipality", type: "municipality", wards: 11 },
          { id: 143, name: "Surunga Municipality", type: "municipality", wards: 10 },
          { id: 144, name: "Hanumannagar Kankalini Municipality", type: "municipality", wards: 11 },
          { id: 145, name: "Khadak Municipality", type: "municipality", wards: 9 },
          { id: 146, name: "Saptakoshi Municipality", type: "municipality", wards: 10 },
          { id: 147, name: "Agnisair Krishna Savaran Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 148, name: "Mahadeva Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 149, name: "Bishnupur Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 150, name: "Chhinnamasta Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 151, name: "Tilathi Koiladi Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 152, name: "Rupani Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 153, name: "Balan Bihul Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 154, name: "Rajgadh Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 16,
        name: "Siraha",
        municipalities: [
          { id: 155, name: "Lahan Municipality", type: "municipality", wards: 19 },
          { id: 156, name: "Siraha Municipality", type: "municipality", wards: 20 },
          { id: 157, name: "Dhangadhimai Municipality", type: "municipality", wards: 14 },
          { id: 158, name: "Mirchaiya Municipality", type: "municipality", wards: 10 },
          { id: 159, name: "Kalyanpur Municipality", type: "municipality", wards: 10 },
          { id: 160, name: "Golbazar Municipality", type: "municipality", wards: 11 },
          { id: 161, name: "Karjanha Municipality", type: "municipality", wards: 9 },
          { id: 162, name: "Sukhipur Municipality", type: "municipality", wards: 9 },
          { id: 163, name: "Bhagawanpur Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 164, name: "Aurahi Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 165, name: "Bishnupur Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 166, name: "Bariyarpatti Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 167, name: "Lakshmipur Patari Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 168, name: "Naraha Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 169, name: "Sakhuwanankarkatti Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 170, name: "Arnama Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 171, name: "Navarajpur Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 17,
        name: "Dhanusha",
        municipalities: [
          { id: 172, name: "Janakpur Sub-Metropolitan City", type: "sub-metropolitan", wards: 25 },
          { id: 173, name: "Chhireshwornath Municipality", type: "municipality", wards: 11 },
          { id: 174, name: "Ganeshman Charnath Municipality", type: "municipality", wards: 10 },
          { id: 175, name: "Dhanushadham Municipality", type: "municipality", wards: 10 },
          { id: 176, name: "Nagarain Municipality", type: "municipality", wards: 10 },
          { id: 177, name: "Bideha Municipality", type: "municipality", wards: 11 },
          { id: 178, name: "Mithila Municipality", type: "municipality", wards: 13 },
          { id: 179, name: "Sahidnagar Municipality", type: "municipality", wards: 9 },
          { id: 180, name: "Kamala Municipality", type: "municipality", wards: 9 },
          { id: 181, name: "Mithila Bihari Municipality", type: "municipality", wards: 10 },
          { id: 182, name: "Hansapur Municipality", type: "municipality", wards: 9 },
          { id: 183, name: "Janaknandini Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 184, name: "Bateshwar Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 185, name: "Mukhiyapatti Musaharmiya Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 186, name: "Lakshminiya Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 187, name: "Aaurahi Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 188, name: "Dhanauji Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 18,
        name: "Mahottari",
        municipalities: [
          { id: 189, name: "Jaleshwar Municipality", type: "municipality", wards: 11 },
          { id: 190, name: "Bardibas Municipality", type: "municipality", wards: 12 },
          { id: 191, name: "Gaushala Municipality", type: "municipality", wards: 12 },
          { id: 192, name: "Loharpatti Municipality", type: "municipality", wards: 9 },
          { id: 193, name: "Ramgopalpur Municipality", type: "municipality", wards: 9 },
          { id: 194, name: "Aurahi Municipality", type: "municipality", wards: 9 },
          { id: 195, name: "Balwa Municipality", type: "municipality", wards: 11 },
          { id: 196, name: "Manra Siswa Municipality", type: "municipality", wards: 10 },
          { id: 197, name: "Matihani Municipality", type: "municipality", wards: 9 },
          { id: 198, name: "Bhangaha Municipality", type: "municipality", wards: 9 },
          { id: 199, name: "Ekdara Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 200, name: "Samsi Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 201, name: "Sonama Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 202, name: "Pipra Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 203, name: "Mahottari Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 19,
        name: "Sarlahi",
        municipalities: [
          { id: 204, name: "Malangwa Municipality", type: "municipality", wards: 11 },
          { id: 205, name: "Lalbandi Municipality", type: "municipality", wards: 13 },
          { id: 206, name: "Haripur Municipality", type: "municipality", wards: 10 },
          { id: 207, name: "Ishworpur Municipality", type: "municipality", wards: 9 },
          { id: 208, name: "Godaita Municipality", type: "municipality", wards: 11 },
          { id: 209, name: "Barahathwa Municipality", type: "municipality", wards: 10 },
          { id: 210, name: "Hariwan Municipality", type: "municipality", wards: 13 },
          { id: 211, name: "Bagmati Municipality", type: "municipality", wards: 10 },
          { id: 212, name: "Balara Municipality", type: "municipality", wards: 9 },
          { id: 213, name: "Kabilasi Municipality", type: "municipality", wards: 9 },
          { id: 214, name: "Chandranagar Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 215, name: "Dhankaul Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 216, name: "Parsa Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 217, name: "Bishnu Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 218, name: "Ramnagar Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 219, name: "Kaudena Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 220, name: "Basbariya Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 221, name: "Chakraghatta Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 222, name: "Bramhapuri Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 223, name: "Nawalpur Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 20,
        name: "Rautahat",
        municipalities: [
          { id: 224, name: "Gaur Municipality", type: "municipality", wards: 13 },
          { id: 225, name: "Chandrapur Municipality", type: "municipality", wards: 10 },
          { id: 226, name: "Garuda Municipality", type: "municipality", wards: 9 },
          { id: 227, name: "Brindaban Municipality", type: "municipality", wards: 10 },
          { id: 228, name: "Gujara Municipality", type: "municipality", wards: 9 },
          { id: 229, name: "Gadhimai Municipality", type: "municipality", wards: 11 },
          { id: 230, name: "Baudhimai Municipality", type: "municipality", wards: 9 },
          { id: 231, name: "Dewahi Gonahi Municipality", type: "municipality", wards: 11 },
          { id: 232, name: "Ishanath Municipality", type: "municipality", wards: 9 },
          { id: 233, name: "Maulapur Municipality", type: "municipality", wards: 9 },
          { id: 234, name: "Madhav Narayan Municipality", type: "municipality", wards: 9 },
          { id: 235, name: "Paroha Municipality", type: "municipality", wards: 10 },
          { id: 236, name: "Phatuwa Bijayapur Municipality", type: "municipality", wards: 9 },
          { id: 237, name: "Rajpur Municipality", type: "municipality", wards: 9 },
          { id: 238, name: "Rajdevi Municipality", type: "municipality", wards: 9 },
          { id: 239, name: "Durga Bhagwati Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 240, name: "Yamunamai Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 241, name: "Katahariya Municipality", type: "municipality", wards: 9 },
        ],
      },
      {
        id: 21,
        name: "Bara",
        municipalities: [
          { id: 242, name: "Kalaiya Sub-Metropolitan City", type: "sub-metropolitan", wards: 22 },
          { id: 243, name: "Jeetpur Simara Sub-Metropolitan City", type: "sub-metropolitan", wards: 19 },
          { id: 244, name: "Kolhabi Municipality", type: "municipality", wards: 11 },
          { id: 245, name: "Nijgadh Municipality", type: "municipality", wards: 11 },
          { id: 246, name: "Mahagadhimai Municipality", type: "municipality", wards: 11 },
          { id: 247, name: "Simraungadh Municipality", type: "municipality", wards: 13 },
          { id: 248, name: "Pacharauta Municipality", type: "municipality", wards: 11 },
          { id: 249, name: "Pheta Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 250, name: "Devtal Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 251, name: "Karaiyamai Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 252, name: "Suwarna Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 253, name: "Baragadhi Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 254, name: "Adarsh Kotwal Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 255, name: "Prasauni Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 256, name: "Bishrampur Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 257, name: "Parwanipur Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 22,
        name: "Parsa",
        municipalities: [
          { id: 258, name: "Birgunj Metropolitan City", type: "metropolitan", wards: 32 },
          { id: 259, name: "Pokhariya Municipality", type: "municipality", wards: 12 },
          { id: 260, name: "Bahudarmai Municipality", type: "municipality", wards: 9 },
          { id: 261, name: "Parsagadhi Municipality", type: "municipality", wards: 13 },
          { id: 262, name: "Bindabasini Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 263, name: "Dhobini Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 264, name: "Chhipaharmai Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 265, name: "Jagarnathpur Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 266, name: "Jirabhawani Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 267, name: "Kalikamai Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 268, name: "Pakaha Mainpur Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 269, name: "Paterwa Sugauli Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 270, name: "Sakhuwa Prasauni Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 271, name: "Thori Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Bagmati Pradesh",
    districts: [
      {
        id: 23,
        name: "Dolakha",
        municipalities: [
          { id: 272, name: "Bhimeshwar Municipality", type: "municipality", wards: 9 },
          { id: 273, name: "Jiri Municipality", type: "municipality", wards: 9 },
          { id: 274, name: "Kalinchowk Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 275, name: "Melung Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 276, name: "Bigu Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 277, name: "Gaurishankar Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 278, name: "Baiteshwar Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 279, name: "Sailung Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 280, name: "Tamakoshi Rural Municipality", type: "rural-municipality", wards: 7 },
        ],
      },
      {
        id: 24,
        name: "Sindhupalchok",
        municipalities: [
          { id: 281, name: "Chautara Sangachowkgadhi Municipality", type: "municipality", wards: 11 },
          { id: 282, name: "Melamchi Municipality", type: "municipality", wards: 13 },
          { id: 283, name: "Bahrabise Municipality", type: "municipality", wards: 9 },
          { id: 284, name: "Panchpokhari Thangpal Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 285, name: "Jugal Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 286, name: "Balefi Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 287, name: "Helambu Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 288, name: "Indrawati Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 289, name: "Tripurasundari Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 290, name: "Lisankhu Pakhar Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 291, name: "Sunkoshi Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 292, name: "Bhotekoshi Rural Municipality", type: "rural-municipality", wards: 6 },
        ],
      },
      {
        id: 25,
        name: "Rasuwa",
        municipalities: [
          { id: 293, name: "Uttargaya Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 294, name: "Kalika Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 295, name: "Naukunda Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 296, name: "Parbati Kunda Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 297, name: "Gosaikunda Rural Municipality", type: "rural-municipality", wards: 7 },
        ],
      },
      {
        id: 26,
        name: "Nuwakot",
        municipalities: [
          { id: 298, name: "Bidur Municipality", type: "municipality", wards: 13 },
          { id: 299, name: "Belkotgadhi Municipality", type: "municipality", wards: 13 },
          { id: 300, name: "Kakani Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 301, name: "Dupcheshwar Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 302, name: "Shivapuri Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 303, name: "Kispang Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 304, name: "Myagang Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 305, name: "Tadi Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 306, name: "Likhu Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 307, name: "Suryagadhi Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 308, name: "Tarkeshwar Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 309, name: "Panchakanya Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 27,
        name: "Dhading",
        municipalities: [
          { id: 310, name: "Dhunibeshi Municipality", type: "municipality", wards: 9 },
          { id: 311, name: "Nilkantha Municipality", type: "municipality", wards: 14 },
          { id: 312, name: "Benighat Rorang Rural Municipality", type: "rural-municipality", wards: 12 },
          { id: 313, name: "Galchhi Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 314, name: "Gangajamuna Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 315, name: "Gajuri Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 316, name: "Jwalamukhi Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 317, name: "Khaniyabash Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 318, name: "Netrawati Dabjong Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 319, name: "Rubi Valley Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 320, name: "Siddhalek Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 321, name: "Thakre Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 322, name: "Tripurasundari Rural Municipality", type: "rural-municipality", wards: 6 },
        ],
      },
      {
        id: 28,
        name: "Makwanpur",
        municipalities: [
          { id: 323, name: "Hetauda Sub-Metropolitan City", type: "sub-metropolitan", wards: 19 },
          { id: 324, name: "Thaha Municipality", type: "municipality", wards: 12 },
          { id: 325, name: "Bhimphedi Rural Municipality", type: "rural-municipality", wards: 10 },
          { id: 326, name: "Makawanpurgadhi Rural Municipality", type: "rural-municipality", wards: 10 },
          { id: 327, name: "Manahari Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 328, name: "Raksirang Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 329, name: "Bakaiya Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 330, name: "Bagmati Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 331, name: "Kailash Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 332, name: "Indrasarowar Rural Municipality", type: "rural-municipality", wards: 7 },
        ],
      },
      {
        id: 29,
        name: "Chitwan",
        municipalities: [
          { id: 333, name: "Bharatpur Metropolitan City", type: "metropolitan", wards: 29 },
          { id: 334, name: "Ratnanagar Municipality", type: "municipality", wards: 16 },
          { id: 335, name: "Khairahani Municipality", type: "municipality", wards: 13 },
          { id: 336, name: "Madi Municipality", type: "municipality", wards: 10 },
          { id: 337, name: "Rapti Municipality", type: "municipality", wards: 12 },
          { id: 338, name: "Kalika Municipality", type: "municipality", wards: 11 },
          { id: 339, name: "Ichchhakamana Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 30,
        name: "Ramechhap",
        municipalities: [
          { id: 340, name: "Manthali Municipality", type: "municipality", wards: 14 },
          { id: 341, name: "Ramechhap Municipality", type: "municipality", wards: 9 },
          { id: 342, name: "Umakunda Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 343, name: "Khandadevi Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 344, name: "Gokulganga Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 345, name: "Doramba Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 346, name: "Likhu Tamakoshi Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 347, name: "Sunapati Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 31,
        name: "Sindhuli",
        municipalities: [
          { id: 348, name: "Kamalamai Municipality", type: "municipality", wards: 14 },
          { id: 349, name: "Dudhauli Municipality", type: "municipality", wards: 13 },
          { id: 350, name: "Golanjor Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 351, name: "Ghyanglekh Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 352, name: "Hariharpurgadhi Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 353, name: "Marin Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 354, name: "Phikkal Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 355, name: "Sunkoshi Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 356, name: "Tinpatan Rural Municipality", type: "rural-municipality", wards: 6 },
        ],
      },
      {
        id: 32,
        name: "Kavrepalanchok",
        municipalities: [
          { id: 357, name: "Dhulikhel Municipality", type: "municipality", wards: 12 },
          { id: 358, name: "Banepa Municipality", type: "municipality", wards: 14 },
          { id: 359, name: "Panauti Municipality", type: "municipality", wards: 11 },
          { id: 360, name: "Namobuddha Municipality", type: "municipality", wards: 11 },
          { id: 361, name: "Panchkhal Municipality", type: "municipality", wards: 12 },
          { id: 362, name: "Mandandeupur Municipality", type: "municipality", wards: 12 },
          { id: 363, name: "Khanikhola Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 364, name: "Chauri Deurali Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 365, name: "Temal Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 366, name: "Bhumlu Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 367, name: "Bethanchowk Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 368, name: "Roshi Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 369, name: "Mahabharat Rural Municipality", type: "rural-municipality", wards: 8 },
        ],
      },
      {
        id: 33,
        name: "Lalitpur",
        municipalities: [
          { id: 370, name: "Lalitpur Metropolitan City", type: "metropolitan", wards: 29 },
          { id: 371, name: "Godawari Municipality", type: "municipality", wards: 14 },
          { id: 372, name: "Mahalaxmi Municipality", type: "municipality", wards: 10 },
          { id: 373, name: "Konjyosom Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 374, name: "Bagmati Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 375, name: "Mahankal Rural Municipality", type: "rural-municipality", wards: 6 },
        ],
      },
      {
        id: 34,
        name: "Bhaktapur",
        municipalities: [
          { id: 376, name: "Bhaktapur Municipality", type: "municipality", wards: 17 },
          { id: 377, name: "Madhyapur Thimi Municipality", type: "municipality", wards: 9 },
          { id: 378, name: "Suryabinayak Municipality", type: "municipality", wards: 10 },
          { id: 379, name: "Changunarayan Municipality", type: "municipality", wards: 9 },
        ],
      },
      {
        id: 35,
        name: "Kathmandu",
        municipalities: [
          { id: 380, name: "Kathmandu Metropolitan City", type: "metropolitan", wards: 32 },
          { id: 381, name: "Kageshwori Manohara Municipality", type: "municipality", wards: 9 },
          { id: 382, name: "Kirtipur Municipality", type: "municipality", wards: 10 },
          { id: 383, name: "Gokarneshwar Municipality", type: "municipality", wards: 9 },
          { id: 384, name: "Chandragiri Municipality", type: "municipality", wards: 15 },
          { id: 385, name: "Tokha Municipality", type: "municipality", wards: 11 },
          { id: 386, name: "Tarkeshwar Municipality", type: "municipality", wards: 11 },
          { id: 387, name: "Nagarjun Municipality", type: "municipality", wards: 10 },
          { id: 388, name: "Budhanilkantha Municipality", type: "municipality", wards: 13 },
          { id: 389, name: "Tarakeshwar Municipality", type: "municipality", wards: 11 },
          { id: 390, name: "Dakshinkali Municipality", type: "municipality", wards: 9 },
          { id: 391, name: "Shankharapur Municipality", type: "municipality", wards: 9 },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "Gandaki Pradesh",
    districts: [
      {
        id: 36,
        name: "Gorkha",
        municipalities: [
          { id: 392, name: "Gorkha Municipality", type: "municipality", wards: 14 },
          { id: 393, name: "Palungtar Municipality", type: "municipality", wards: 11 },
          { id: 394, name: "Sulikot Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 395, name: "Siranchowk Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 396, name: "Ajirkot Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 397, name: "Aarughat Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 398, name: "Bhimsen Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 399, name: "Dharche Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 400, name: "Gandaki Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 401, name: "Shahid Lakhan Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 402, name: "Barpak Sulikot Rural Municipality", type: "rural-municipality", wards: 8 },
        ],
      },
      {
        id: 37,
        name: "Lamjung",
        municipalities: [
          { id: 403, name: "Besishahar Municipality", type: "municipality", wards: 11 },
          { id: 404, name: "Sundarbazar Municipality", type: "municipality", wards: 10 },
          { id: 405, name: "Rainas Municipality", type: "municipality", wards: 10 },
          { id: 406, name: "Madhya Nepal Municipality", type: "municipality", wards: 9 },
          { id: 407, name: "Dordi Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 408, name: "Dudhpokhari Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 409, name: "Kwholasothar Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 410, name: "Marsyangdi Rural Municipality", type: "rural-municipality", wards: 7 },
        ],
      },
      {
        id: 38,
        name: "Tanahun",
        municipalities: [
          { id: 411, name: "Bhanu Municipality", type: "municipality", wards: 13 },
          { id: 412, name: "Byas Municipality", type: "municipality", wards: 14 },
          { id: 413, name: "Shuklagandaki Municipality", type: "municipality", wards: 14 },
          { id: 414, name: "Bandipur Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 415, name: "Ghiring Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 416, name: "Devghat Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 417, name: "Myagde Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 418, name: "Anbukhaireni Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 419, name: "Rishing Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 420, name: "Bhimad Municipality", type: "municipality", wards: 12 },
        ],
      },
      {
        id: 39,
        name: "Syangja",
        municipalities: [
          { id: 421, name: "Putalibazar Municipality", type: "municipality", wards: 14 },
          { id: 422, name: "Galyang Municipality", type: "municipality", wards: 11 },
          { id: 423, name: "Chapakot Municipality", type: "municipality", wards: 13 },
          { id: 424, name: "Waling Municipality", type: "municipality", wards: 14 },
          { id: 425, name: "Bhirkot Municipality", type: "municipality", wards: 10 },
          { id: 426, name: "Arjunchaupari Rural Municipality", type: "rural-municipality", wards: 10 },
          { id: 427, name: "Aandhikhola Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 428, name: "Phedikhola Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 429, name: "Harinas Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 430, name: "Biruwa Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 431, name: "Kaligandaki Rural Municipality", type: "rural-municipality", wards: 6 },
        ],
      },
      {
        id: 40,
        name: "Kaski",
        municipalities: [
          { id: 432, name: "Pokhara Metropolitan City", type: "metropolitan", wards: 33 },
          { id: 433, name: "Annapurna Rural Municipality", type: "rural-municipality", wards: 11 },
          { id: 434, name: "Machhapuchchhre Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 435, name: "Madi Rural Municipality", type: "rural-municipality", wards: 12 },
          { id: 436, name: "Rupa Rural Municipality", type: "rural-municipality", wards: 7 },
        ],
      },
      {
        id: 41,
        name: "Manang",
        municipalities: [
          { id: 437, name: "Chame Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 438, name: "Nashong Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 439, name: "Narpa Bhumi Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 440, name: "Manang Ngisyang Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 42,
        name: "Mustang",
        municipalities: [
          { id: 441, name: "Gharapjhong Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 442, name: "Thasang Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 443, name: "Lomanthang Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 444, name: "Lo-Ghekar Damodarkunda Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 445, name: "Barhagaun Muktichhetra Rural Municipality", type: "rural-municipality", wards: 7 },
        ],
      },
      {
        id: 43,
        name: "Myagdi",
        municipalities: [
          { id: 446, name: "Beni Municipality", type: "municipality", wards: 11 },
          { id: 447, name: "Annapurna Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 448, name: "Dhaulagiri Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 449, name: "Mangala Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 450, name: "Malika Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 451, name: "Raghuganga Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 44,
        name: "Parbat",
        municipalities: [
          { id: 452, name: "Kushma Municipality", type: "municipality", wards: 14 },
          { id: 453, name: "Phalebas Municipality", type: "municipality", wards: 12 },
          { id: 454, name: "Jaljala Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 455, name: "Modi Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 456, name: "Mahashila Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 457, name: "Bihadi Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 458, name: "Paiyun Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 45,
        name: "Baglung",
        municipalities: [
          { id: 459, name: "Baglung Municipality", type: "municipality", wards: 14 },
          { id: 460, name: "Galkot Municipality", type: "municipality", wards: 11 },
          { id: 461, name: "Jaimini Municipality", type: "municipality", wards: 11 },
          { id: 462, name: "Dhorpatan Municipality", type: "municipality", wards: 10 },
          { id: 463, name: "Bareng Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 464, name: "Kanthekhola Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 465, name: "Taman Khola Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 466, name: "Tara Khola Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 467, name: "Nisikhola Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 468, name: "Kathekhola Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 46,
        name: "Nawalpur",
        municipalities: [
          { id: 469, name: "Kawasoti Municipality", type: "municipality", wards: 16 },
          { id: 470, name: "Gaindakot Municipality", type: "municipality", wards: 13 },
          { id: 471, name: "Devchuli Municipality", type: "municipality", wards: 15 },
          { id: 472, name: "Madhyabindu Municipality", type: "municipality", wards: 13 },
          { id: 473, name: "Binayi Tribeni Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 474, name: "Bulingtar Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 475, name: "Hupsekot Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 476, name: "Baudikali Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
    ],
  },
  {
    id: 5,
    name: "Lumbini Pradesh",
    districts: [
      {
        id: 47,
        name: "Rupandehi",
        municipalities: [
          { id: 477, name: "Butwal Sub-Metropolitan City", type: "sub-metropolitan", wards: 19 },
          { id: 478, name: "Siddharthanagar Municipality", type: "municipality", wards: 13 },
          { id: 479, name: "Devdaha Municipality", type: "municipality", wards: 11 },
          { id: 480, name: "Lumbini Sanskritik Municipality", type: "municipality", wards: 13 },
          { id: 481, name: "Sainamaina Municipality", type: "municipality", wards: 12 },
          { id: 482, name: "Tillotama Municipality", type: "municipality", wards: 17 },
          { id: 483, name: "Rohini Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 484, name: "Gaidhawa Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 485, name: "Kanchan Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 486, name: "Siyari Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 487, name: "Marchawari Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 488, name: "Kotahimai Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 489, name: "Mayadevi Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 490, name: "Sudhdhodhan Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 491, name: "Omsatiya Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 492, name: "Sammarimai Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 48,
        name: "Kapilvastu",
        municipalities: [
          { id: 493, name: "Kapilvastu Municipality", type: "municipality", wards: 11 },
          { id: 494, name: "Buddhabhatri Municipality", type: "municipality", wards: 11 },
          { id: 495, name: "Shivaraj Municipality", type: "municipality", wards: 11 },
          { id: 496, name: "Maharajgunj Municipality", type: "municipality", wards: 9 },
          { id: 497, name: "Krishnanagar Municipality", type: "municipality", wards: 9 },
          { id: 498, name: "Banganga Municipality", type: "municipality", wards: 12 },
          { id: 499, name: "Bijaynagar Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 500, name: "Mayadevi Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 501, name: "Suddhodhan Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 502, name: "Yashodhara Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 49,
        name: "Arghakhanchi",
        municipalities: [
          { id: 503, name: "Sandhikharka Municipality", type: "municipality", wards: 11 },
          { id: 504, name: "Sitganga Municipality", type: "municipality", wards: 12 },
          { id: 505, name: "Bhumikasthan Municipality", type: "municipality", wards: 10 },
          { id: 506, name: "Chhatradev Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 507, name: "Panini Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 508, name: "Malarani Rural Municipality", type: "rural-municipality", wards: 6 },
        ],
      },
      {
        id: 50,
        name: "Gulmi",
        municipalities: [
          { id: 509, name: "Resunga Municipality", type: "municipality", wards: 14 },
          { id: 510, name: "Musikot Municipality", type: "municipality", wards: 10 },
          { id: 511, name: "Isma Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 512, name: "Chandrakot Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 513, name: "Satyawati Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 514, name: "Dhurkot Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 515, name: "Chatrakot Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 516, name: "Gulmi Darbar Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 517, name: "Madane Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 518, name: "Malika Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 519, name: "Kaligandaki Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 520, name: "Ruru Rural Municipality", type: "rural-municipality", wards: 6 },
        ],
      },
      {
        id: 51,
        name: "Palpa",
        municipalities: [
          { id: 521, name: "Tansen Municipality", type: "municipality", wards: 14 },
          { id: 522, name: "Rampur Municipality", type: "municipality", wards: 11 },
          { id: 523, name: "Bagnaskali Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 524, name: "Mathagadhi Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 525, name: "Nisdi Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 526, name: "Purbakhola Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 527, name: "Rambha Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 528, name: "Rainadevi Chhahara Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 529, name: "Tinau Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 530, name: "Ribdikot Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 52,
        name: "Nawalparasi West (Parasi)",
        municipalities: [
          { id: 531, name: "Bardaghat Municipality", type: "municipality", wards: 13 },
          { id: 532, name: "Ramgram Municipality", type: "municipality", wards: 14 },
          { id: 533, name: "Sunwal Municipality", type: "municipality", wards: 13 },
          { id: 534, name: "Susta Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 535, name: "Palhinandan Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 536, name: "Pratappur Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 537, name: "Sarawal Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 53,
        name: "Dang",
        municipalities: [
          { id: 538, name: "Ghorahi Sub-Metropolitan City", type: "sub-metropolitan", wards: 19 },
          { id: 539, name: "Tulsipur Sub-Metropolitan City", type: "sub-metropolitan", wards: 19 },
          { id: 540, name: "Lamahi Municipality", type: "municipality", wards: 9 },
          { id: 541, name: "Bangalachuli Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 542, name: "Dangisharan Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 543, name: "Gadhawa Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 544, name: "Rajpur Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 545, name: "Rapti Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 546, name: "Shantinagar Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 547, name: "Babai Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 54,
        name: "Pyuthan",
        municipalities: [
          { id: 548, name: "Pyuthan Municipality", type: "municipality", wards: 11 },
          { id: 549, name: "Swargadwari Municipality", type: "municipality", wards: 11 },
          { id: 550, name: "Gaumukhi Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 551, name: "Mandavi Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 552, name: "Mallarani Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 553, name: "Naubahini Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 554, name: "Jhimruk Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 555, name: "Airawati Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 556, name: "Sarumarani Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 55,
        name: "Rolpa",
        municipalities: [
          { id: 557, name: "Rolpa Municipality", type: "municipality", wards: 10 },
          { id: 558, name: "Triveni Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 559, name: "Runtigadhi Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 560, name: "Lungri Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 561, name: "Gangadev Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 562, name: "Sunchhahari Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 563, name: "Thabang Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 564, name: "Madi Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 565, name: "Paribartan Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 566, name: "Sukidaha Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 56,
        name: "Eastern Rukum",
        municipalities: [
          { id: 567, name: "Rukum Municipality", type: "municipality", wards: 9 },
          { id: 568, name: "Bhume Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 569, name: "Sisne Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 570, name: "Putha Uttarganga Rural Municipality", type: "rural-municipality", wards: 11 },
        ],
      },
      {
        id: 57,
        name: "Banke",
        municipalities: [
          { id: 571, name: "Nepalgunj Sub-Metropolitan City", type: "sub-metropolitan", wards: 23 },
          { id: 572, name: "Kohalpur Municipality", type: "municipality", wards: 15 },
          { id: 573, name: "Narainapur Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 574, name: "Rapti Sonari Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 575, name: "Baijanath Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 576, name: "Khajura Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 577, name: "Duduwa Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 578, name: "Janaki Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 58,
        name: "Bardiya",
        municipalities: [
          { id: 579, name: "Gulariya Municipality", type: "municipality", wards: 12 },
          { id: 580, name: "Rajapur Municipality", type: "municipality", wards: 10 },
          { id: 581, name: "Madhuwan Municipality", type: "municipality", wards: 10 },
          { id: 582, name: "Thakurbaba Municipality", type: "municipality", wards: 11 },
          { id: 583, name: "Bansgadhi Municipality", type: "municipality", wards: 9 },
          { id: 584, name: "Barbardiya Municipality", type: "municipality", wards: 10 },
          { id: 585, name: "Geruwa Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 586, name: "Badhaiyatal Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
    ],
  },
  {
    id: 6,
    name: "Karnali Pradesh",
    districts: [
      {
        id: 59,
        name: "Western Rukum",
        municipalities: [
          { id: 587, name: "Musikot Municipality", type: "municipality", wards: 14 },
          { id: 588, name: "Chaurjahari Municipality", type: "municipality", wards: 12 },
          { id: 589, name: "Aathbiskot Municipality", type: "municipality", wards: 11 },
          { id: 590, name: "Banphikot Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 591, name: "Tribeni Rural Municipality", type: "rural-municipality", wards: 8 },
          { id: 592, name: "Sani Bheri Rural Municipality", type: "rural-municipality", wards: 7 },
        ],
      },
      {
        id: 60,
        name: "Salyan",
        municipalities: [
          { id: 593, name: "Shaarda Municipality", type: "municipality", wards: 12 },
          { id: 594, name: "Bangad Kupinde Municipality", type: "municipality", wards: 12 },
          { id: 595, name: "Bagchaur Municipality", type: "municipality", wards: 12 },
          { id: 596, name: "Kalimati Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 597, name: "Tribeni Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 598, name: "Kapurkot Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 599, name: "Chhatreshwari Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 600, name: "Kumakh Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 601, name: "Siddha Kumakh Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 602, name: "Darma Rural Municipality", type: "rural-municipality", wards: 6 },
        ],
      },
      {
        id: 61,
        name: "Dolpa",
        municipalities: [
          { id: 603, name: "Thuli Bheri Municipality", type: "municipality", wards: 10 },
          { id: 604, name: "Tripurasundari Municipality", type: "municipality", wards: 9 },
          { id: 605, name: "Dolpo Buddha Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 606, name: "Shey Phoksundo Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 607, name: "Jagadulla Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 608, name: "Mudkechula Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 609, name: "Kaike Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 610, name: "Chharka Tangsong Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 62,
        name: "Humla",
        municipalities: [
          { id: 611, name: "Simkot Rural Municipality", type: "rural-municipality", wards: 9 },
          { id: 612, name: "Namkha Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 613, name: "Kharpunath Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 614, name: "Sarkegad Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 615, name: "Adanchuli Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 616, name: "Tanjakot Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 617, name: "Chankheli Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 63,
        name: "Jumla",
        municipalities: [
          { id: 618, name: "Chandannath Municipality", type: "municipality", wards: 9 },
          { id: 619, name: "Kankasundari Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 620, name: "Sinja Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 621, name: "Hima Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 622, name: "Tila Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 623, name: "Guthichaur Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 624, name: "Tatopani Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 625, name: "Patarasi Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 64,
        name: "Kalikot",
        municipalities: [
          { id: 626, name: "Khandachakra Municipality", type: "municipality", wards: 10 },
          { id: 627, name: "Raskot Municipality", type: "municipality", wards: 10 },
          { id: 628, name: "Tilagufa Municipality", type: "municipality", wards: 9 },
          { id: 629, name: "Pachaljharana Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 630, name: "Sanni Triveni Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 631, name: "Naraharinath Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 632, name: "Shubha Kalika Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 633, name: "Mahawai Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 634, name: "Palata Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 65,
        name: "Mugu",
        municipalities: [
          { id: 635, name: "Chhayanath Rara Municipality", type: "municipality", wards: 11 },
          { id: 636, name: "Mugum Karmarong Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 637, name: "Soru Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 638, name: "Khatyad Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 66,
        name: "Surkhet",
        municipalities: [
          { id: 639, name: "Birendranagar Municipality", type: "municipality", wards: 16 },
          { id: 640, name: "Bheriganga Municipality", type: "municipality", wards: 14 },
          { id: 641, name: "Gurbhakot Municipality", type: "municipality", wards: 13 },
          { id: 642, name: "Panchapuri Municipality", type: "municipality", wards: 11 },
          { id: 643, name: "Lekbeshi Municipality", type: "municipality", wards: 10 },
          { id: 644, name: "Chaukune Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 645, name: "Barahatal Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 646, name: "Simta Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 647, name: "Chingad Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 67,
        name: "Dailekh",
        municipalities: [
          { id: 648, name: "Narayan Municipality", type: "municipality", wards: 12 },
          { id: 649, name: "Dullu Municipality", type: "municipality", wards: 12 },
          { id: 650, name: "Aathbis Municipality", type: "municipality", wards: 9 },
          { id: 651, name: "Chamunda Bindrasaini Municipality", type: "municipality", wards: 11 },
          { id: 652, name: "Bhagawatimai Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 653, name: "Bhairabi Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 654, name: "Dungeshwar Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 655, name: "Gurans Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 656, name: "Mahabu Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 657, name: "Naumule Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 658, name: "Thantikandh Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 68,
        name: "Jajarkot",
        municipalities: [
          { id: 659, name: "Bheri Municipality", type: "municipality", wards: 14 },
          { id: 660, name: "Chhedagad Municipality", type: "municipality", wards: 11 },
          { id: 661, name: "Nalgad Municipality", type: "municipality", wards: 9 },
          { id: 662, name: "Junichande Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 663, name: "Kuse Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 664, name: "Barekot Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 665, name: "Shivalaya Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
    ],
  },
  {
    id: 7,
    name: "Sudurpashchim Pradesh",
    districts: [
      {
        id: 69,
        name: "Bajura",
        municipalities: [
          { id: 666, name: "Badimalika Municipality", type: "municipality", wards: 12 },
          { id: 667, name: "Triveni Municipality", type: "municipality", wards: 9 },
          { id: 668, name: "Budhiganga Municipality", type: "municipality", wards: 9 },
          { id: 669, name: "Budhinanda Municipality", type: "municipality", wards: 9 },
          { id: 670, name: "Gaumul Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 671, name: "Pandav Gupha Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 672, name: "Swamikartik Khapar Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 673, name: "Chhededaha Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 674, name: "Himali Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 70,
        name: "Bajhang",
        municipalities: [
          { id: 675, name: "Jayaprithvi Municipality", type: "municipality", wards: 11 },
          { id: 676, name: "Bungal Municipality", type: "municipality", wards: 10 },
          { id: 677, name: "Thalara Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 678, name: "Bitthadchir Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 679, name: "Surma Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 680, name: "Chabispathivera Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 681, name: "Durgathali Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 682, name: "Kedarsyu Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 683, name: "Khaptad Chhanna Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 684, name: "Masta Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 685, name: "Saipal Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 686, name: "Talkot Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 71,
        name: "Darchula",
        municipalities: [
          { id: 687, name: "Mahakali Municipality", type: "municipality", wards: 10 },
          { id: 688, name: "Shailyashikhar Municipality", type: "municipality", wards: 9 },
          { id: 689, name: "Malikarjun Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 690, name: "Apihimal Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 691, name: "Duhun Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 692, name: "Marma Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 693, name: "Lekam Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 694, name: "Naugad Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 695, name: "Vyans Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 72,
        name: "Baitadi",
        municipalities: [
          { id: 696, name: "Dasharathchanda Municipality", type: "municipality", wards: 9 },
          { id: 697, name: "Patan Municipality", type: "municipality", wards: 11 },
          { id: 698, name: "Melauli Municipality", type: "municipality", wards: 10 },
          { id: 699, name: "Purchaudi Municipality", type: "municipality", wards: 9 },
          { id: 700, name: "Dogadakedar Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 701, name: "Dilasaini Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 702, name: "Pancheshwar Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 703, name: "Sigas Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 704, name: "Shivanath Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 705, name: "Surnaya Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 73,
        name: "Dadeldhura",
        municipalities: [
          { id: 706, name: "Amargadhi Municipality", type: "municipality", wards: 11 },
          { id: 707, name: "Parshuram Municipality", type: "municipality", wards: 10 },
          { id: 708, name: "Aalitaal Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 709, name: "Bhageshwar Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 710, name: "Nawadurga Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 711, name: "Ajaymeru Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 712, name: "Ganyapadhura Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 74,
        name: "Doti",
        municipalities: [
          { id: 713, name: "Dipayal Silgadhi Municipality", type: "municipality", wards: 15 },
          { id: 714, name: "Shikhar Municipality", type: "municipality", wards: 12 },
          { id: 715, name: "Adharsha Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 716, name: "Badikedar Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 717, name: "Bogatan Phukan Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 718, name: "Jorayal Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 719, name: "K I Singh Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 720, name: "Purbichauki Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 721, name: "Sayal Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 75,
        name: "Achham",
        municipalities: [
          { id: 722, name: "Mangalsen Municipality", type: "municipality", wards: 14 },
          { id: 723, name: "Kamalbazar Municipality", type: "municipality", wards: 11 },
          { id: 724, name: "Sanfebagar Municipality", type: "municipality", wards: 13 },
          { id: 725, name: "Panchadewal Binayak Municipality", type: "municipality", wards: 11 },
          { id: 726, name: "Bannigadhi Jayagadh Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 727, name: "Chaurpati Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 728, name: "Dhakari Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 729, name: "Mellekh Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 730, name: "Ramaroshan Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 731, name: "Turmakhand Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
      {
        id: 76,
        name: "Kailali",
        municipalities: [
          { id: 732, name: "Dhangadhi Sub-Metropolitan City", type: "sub-metropolitan", wards: 19 },
          { id: 733, name: "Tikapur Municipality", type: "municipality", wards: 9 },
          { id: 734, name: "Ghodaghodi Municipality", type: "municipality", wards: 12 },
          { id: 735, name: "Lamkichuha Municipality", type: "municipality", wards: 9 },
          { id: 736, name: "Bhajani Municipality", type: "municipality", wards: 9 },
          { id: 737, name: "Godawari Municipality", type: "municipality", wards: 12 },
          { id: 738, name: "Gauriganga Municipality", type: "municipality", wards: 10 },
          { id: 739, name: "Janaki Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 740, name: "Bardagoriya Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 741, name: "Mohanyal Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 742, name: "Kailari Rural Municipality", type: "rural-municipality", wards: 7 },
          { id: 743, name: "Joshipur Rural Municipality", type: "rural-municipality", wards: 5 },
          { id: 744, name: "Chure Rural Municipality", type: "rural-municipality", wards: 7 },
        ],
      },
      {
        id: 77,
        name: "Kanchanpur",
        municipalities: [
          { id: 745, name: "Bhimdatta Municipality", type: "municipality", wards: 19 },
          { id: 746, name: "Punarbas Municipality", type: "municipality", wards: 11 },
          { id: 747, name: "Bedkot Municipality", type: "municipality", wards: 10 },
          { id: 748, name: "Mahakali Municipality", type: "municipality", wards: 9 },
          { id: 749, name: "Shuklaphanta Municipality", type: "municipality", wards: 11 },
          { id: 750, name: "Belauri Municipality", type: "municipality", wards: 10 },
          { id: 751, name: "Krishnapur Municipality", type: "municipality", wards: 9 },
          { id: 752, name: "Beldandi Rural Municipality", type: "rural-municipality", wards: 6 },
          { id: 753, name: "Laljhadi Rural Municipality", type: "rural-municipality", wards: 5 },
        ],
      },
    ],
  },
];

// Helper functions

export function getProvinces(): { id: number; name: string }[] {
  return provinces.map((p) => ({ id: p.id, name: p.name }));
}

export function getDistricts(provinceId: number): { id: number; name: string }[] {
  const province = provinces.find((p) => p.id === provinceId);
  if (!province) return [];
  return province.districts.map((d) => ({ id: d.id, name: d.name }));
}

export function getMunicipalities(districtId: number): { id: number; name: string; type: string }[] {
  for (const province of provinces) {
    const district = province.districts.find((d) => d.id === districtId);
    if (district) {
      return district.municipalities.map((m) => ({
        id: m.id,
        name: m.name,
        type: m.type,
      }));
    }
  }
  return [];
}

export function getWards(municipalityId: number): number[] {
  for (const province of provinces) {
    for (const district of province.districts) {
      const municipality = district.municipalities.find((m) => m.id === municipalityId);
      if (municipality) {
        return Array.from({ length: municipality.wards }, (_, i) => i + 1);
      }
    }
  }
  return [];
}
